# ?????? ?? URL
# jdbc:mysql://localhost:3306/drum: ?????? ?? ??? ??, ?????? ??
# serverTimezone=UTC: MySQL ???? ?? ???? UTC? ??
# characterEncoding=UTF-8: ?????? ???? ???? ?? ???? UTF-8? ??
spring:
  datasource:
    url: jdbc:mysql://j9b107.p.ssafy.io:3500/drum?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: q1w2e3r4
    driver-class-name: com.mysql.cj.jdbc.Driver

# spring.jpa.show-sql: JPA? ???? SQL ??? ??? ???? ??? ??
# spring.jpa.hibernate.ddl-auto: Hibernate? DDL (??? ?? ??) ?? ?? ??? ??
# "none"?? ???? Hibernate? DDL ????? ???? ???? ??

# spring.jpa.properties.hibernate.format_sql: SQL ??? ??? ? SQL ?? ?? ?? ????? ??? ??
# true? ???? SQL ??? ?? ?? ???? ??
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
server:
  port: 8000
  ssl:
        key-store: classpath:keystore.p12
        key-store-password: sssl107
        key-store-type: PKCS12
  servlet:
    context-path: /api/v1
