# ?????? ?? URL
# jdbc:mysql://localhost:3306/drum: ?????? ?? ??? ??, ?????? ??
# serverTimezone=UTC: MySQL ???? ?? ???? UTC? ??
# characterEncoding=UTF-8: ?????? ???? ???? ?? ???? UTF-8? ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drum?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# spring.jpa.show-sql: JPA? ???? SQL ??? ??? ???? ??? ??
# spring.jpa.hibernate.ddl-auto: Hibernate? DDL (??? ?? ??) ?? ?? ??? ??
# "none"?? ???? Hibernate? DDL ????? ???? ???? ??

# spring.jpa.properties.hibernate.format_sql: SQL ??? ??? ? SQL ?? ?? ?? ????? ??? ??
# true? ???? SQL ??? ?? ?? ???? ??
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
server:
  servlet:
    context-path: /api/v1
